apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "my-app-role"
        vault.hashicorp.com/agent-inject-secret-env-vars: "secret/data/my-app/env"
        vault.hashicorp.com/agent-inject-template-env-vars: |
          {{- with secret "secret/data/my-app/env" -}}
          {{- range $k, $v := .Data.data }}
          export {{ $k }}="{{ $v }}"
          {{- end }}
          {{- end -}}
    spec:
      serviceAccountName: my-app-sa
      initContainers:
        - name: wait-for-postgres
          image: postgres:16
          command: ["sh", "-c", "until pg_isready -h postgres-analytics -p 5432; do sleep 2; done"]
      containers:
        - name: analytics
          image: analytics:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5003
          
          # Injects non-sensitive configs from ConfigMap automatically
          envFrom:
            - configMapRef:
                name: app-config
          
          # Load secrets and start the application
          command: ["/bin/sh", "-c"]
          args:
            - |
              . /vault/secrets/env-vars
              exec /docker-entrypoint.sh
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
spec:
  selector:
    app: analytics
  ports:
    - port: 5003
      targetPort: 5003