apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16
          command: ["sh", "-c", "until pg_isready -h postgres-auth -p 5432; do sleep 2; done"]
      containers:
        - name: auth
          image: auth:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_DATABASE_URL
            - name: AUTH_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_SERVICE_PORT
            - name: INTERNAL_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: INTERNAL_API_KEY
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - port: 5001
      targetPort: 5001
