apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campaign
  template:
    metadata:
      labels:
        app: campaign
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "my-app-role"
        vault.hashicorp.com/agent-inject-secret-env-vars: "secret/data/my-app/env"
        vault.hashicorp.com/agent-init-cpu-request: "0"
        vault.hashicorp.com/agent-init-mem-request: "0"
        vault.hashicorp.com/agent-cpu-request: "0"
        vault.hashicorp.com/agent-mem-request: "0"
        vault.hashicorp.com/agent-inject-template-env-vars: |
          {{- with secret "secret/data/my-app/env" -}}
          {{- range $k, $v := .Data.data }}
          export {{ $k }}="{{ $v }}"
          {{- end }}
          {{- end -}}
    spec:
      serviceAccountName: my-app-sa
      initContainers:
        - name: wait-for-postgres
          image: postgres:16
          command: ["sh", "-c", "until pg_isready -h postgres-campaign -p 5432; do sleep 2; done"]
      containers:
        - name: campaign
          image: campaign:latest
          imagePullPolicy: Never
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 5002
          
          # Injeção das configurações que NÃO são segredos (ConfigMap)
          envFrom:
            - configMapRef:
                name: app-config
          
          # Carregamento do Vault e execução da aplicação
          command: ["/bin/sh", "-c"]
          args:
            - |
              . /vault/secrets/env-vars
              
              exec /docker-entrypoint.sh
---
apiVersion: v1
kind: Service
metadata:
  name: campaign
spec:
  selector:
    app: campaign
  ports:
    - port: 5002
      targetPort: 5002