apiVersion: apps/v1
kind: Deployment
metadata:
  name: campaign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: campaign
  template:
    metadata:
      labels:
        app: campaign
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16
          command: ["sh", "-c", "until pg_isready -h postgres-campaign -p 5432; do sleep 2; done"]
      containers:
        - name: campaign
          image: campaign:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CAMPAIGN_DATABASE_URL
            - name: CAMPAIGN_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: CAMPAIGN_SERVICE_PORT
            - name: TRACKING_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TRACKING_BASE_URL
            - name: GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GATEWAY_URL
            - name: INTERNAL_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: INTERNAL_API_KEY
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: campaign
spec:
  selector:
    app: campaign
  ports:
    - port: 5002
      targetPort: 5002
