apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: api-gateway
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort # Use LoadBalancer if deployed on AWS/GCP/Azure
  ports:
    - port: 5000
      targetPort: 80
      nodePort: 30500 # Explicitly targets a port outside the cluster (range 30000-32767)
  selector:
    app: gateway