apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config.yaml
  - postgres.yaml
  - auth.yaml
  - campaign.yaml
  - analytics.yaml
  - email.yaml
  - frontend.yaml
  - gateway.yaml

# nginx.conf mirrors gateway/nginx.conf
configMapGenerator:
  - name: nginx-config
    files:
      - nginx.conf
    options:
      disableNameSuffixHash: true
